export const introNotes = [
  "1. Kwestionariusz jest pomocą w rozeznawaniu charyzmatów osobistych, a nie kompletnym narzędziem. Wypełnienie kwestionariusza nie oznacza rozeznania darów, ponieważ do tego potrzeba jeszcze oddzielenia tego, co jest prawdziwym Bożym wezwaniem od naszych pragnień, projekcji oraz marzeń. Dlatego koniecznym do prawdziwego rozeznania jest praktyka oraz potwierdzenie ze strony innych ludzi, zwłaszcza duszpasterzy.",
  "2. Przed lub po wypełnieniu kwestionariusza dobrze jest przesłuchać wszystkich konferencji o charyzmatach (https://www.youtube.com/playlist?list=PL6hgBhB7Elk-W9cVtuXaRbaCSuyVk6KFw) oraz przeczytać książkę Sherry Weddell „Owocne uczniostwo”.",
  "3. Praktyka oznacza trwający co najmniej kilka miesięcy (lub nawet kilka lat w przypadku charyzmatów stanu życia) czas aktywnego próbowania uczenia się posługi danym charyzmatem. Zalecane jest poświęcenie co najmniej 2 godzin tygodniowo na ten cel. Kolejne miesiące będą przynosiły ważne i cenne w rozeznaniu informacje – czy mam radość w trakcie posługi danym charyzmatem, czy ta posługa jest owocna itp.",
  "4. Potwierdzenie ze strony innych ludzi, zwłaszcza duszpasterzy oznacza konieczność sygnału z zewnątrz w procesie rozeznawania. Cenne są szczególnie te informacje zwrotne, które są spontaniczne. Kwestia potwierdzenia ze strony duszpasterzy jest kluczowa, zwłaszcza w odniesieniu do charyzmatów nadzwyczajnych. Tylko pod stałą opieką duszpasterską te charyzmaty mogą przynosić trwały owoc i harmonijnie znajdować miejsce w parafiach/diecezjach."
] as const

export const instructionText = "Wypełnienie kwestionariusza polega na odniesieniu się do każdego ze 115 zdań w jeden z możliwych sposobów. Odpowiedzi nie powinny wyrażać naszych marzeń (jakim bym chciał być), ale rzeczywistość. Dopiero po skończeniu wszystkich 115 zdań zobaczymy wynik. Suma punktów przy danym charyzmacie jest pomocą w rozeznawaniu."

export const answerScale = [
  {
    "value": 4,
    "label": "w pełni się zgadzam"
  },
  {
    "value": 3,
    "label": "raczej się zgadzam"
  },
  {
    "value": 2,
    "label": "nie jestem zdecydowany"
  },
  {
    "value": 1,
    "label": "raczej się nie zgadzam"
  },
  {
    "value": 0,
    "label": "zupełnie się nie zgadzam"
  }
] as const

export const charisms = [
  "Administracji",
  "Pasterski",
  "Celibatu",
  "Rzemiosła",
  "Dobrowolnego ubóstwa",
  "Ewangelizacji",
  "Zachęty",
  "Pomocy",
  "Dawania",
  "Uzdrawiania",
  "Gościnności",
  "Wstawiennictwa",
  "Wiedzy",
  "Miłosierdzia",
  "Misyjny",
  "Muzyki",
  "Liderski",
  "Wiary",
  "Prorocki",
  "Służby",
  "Nauczania",
  "Pisania",
  "Mądrości/zrozumienia"
] as const

export const questions = [
  "Łatwo przychodzi mi zarządzanie ludźmi i prowadzenie grup, by osiągać konkretne cele.",
  "Lubię organizować małe grupy, w których możemy się poznawać i dzielić wiarą.",
  "Myśl o życiu bez zakładania rodziny mnie nie przeraża.",
  "Dbanie o rzeczy w moim środowisku i naprawianie ich przychodzi mi łatwo.",
  "Czuję się niekomfortowo, gdy mam za dużo rzeczy i pieniędzy.",
  "Lubię mówić o Bogu z osobami, które nie chodzą do kościoła.",
  "Mam radość z motywowania ludzi do głębszego zaangażowania duchowego.",
  "Lubię pomagać księżom/liderom, bo widzę jak wiele spraw mają na głowie.",
  "Odczuwam satysfakcję, kiedy mogę hojnie wspierać finansowo Boże dzieła.",
  "Widok osoby chorej budzi we mnie pragnienie modlitwy za nią.",
  "Mam radość z zapraszania ludzi do mojego domu.",
  "Wyczuwam instynktownie rzeczy, za które trzeba się modlić.",
  "Odczuwam satysfakcję z uczenia się i odkrywania nowych rzeczy.",
  "Szukam okazji, by towarzyszyć ludziom, którzy przeżywają trudności.",
  "Łatwo adaptuję się do innych kultur i nie sprawia mi to trudności.",
  "Lubię śpiewać hymny i pieśni – zarówno samemu jak i z innymi. W ten sposób często się modlę.",
  "Mam w sercu plan, który ufam, że pochodzi od Boga – jak ewangelizować skutecznie w dzisiejszym świecie.",
  "Mocno wierzę, że problemy są wstępem do wielkich Bożych dzieł.",
  "Lubię wsłuchiwać się w Boże natchnienia.",
  "Często angażuje się w prace porządkowe przy kościele.",
  "Odczuwam satysfakcję, pomagając ludziom wgłębiać się w Pismo Święte.",
  "Dotyka mnie piękno słowa pisanego – prozy i poezji.",
  "Ludzie z problemami duchowymi przychodzą do mnie po radę.",
  "Ludzie lubią pracować ze mną, gdy podejmujemy ważne zadania.",
  "Wydaje mi się, że Bóg daje mi mądrość prowadzenia innych w ich życiu duchowym.",
  "Mam często pragnienie bycia z Bogiem sam na sam.",
  "Cieszę się, mogąc tworzyć różnego rodzaju rękodzieła artystyczne.",
  "Mam głębokie przekonanie, że jeśli nie będę zabiegał o pieniądze, to Bóg o wszystko się zatroszczy.",
  "Często zastanawiam się jak mówić innym o Jezusie, by ludzie mogli Go spotkać i stać się Jego uczniami.",
  "Mam dar wydobywania z innych tego, co w nich najlepsze.",
  "Lubię być „na drugiej linii” w ewangelizacji. Robić wszystko co potrzeba, ale z „drugiej linii”.",
  "Chętnie dzielę się z innymi tym, co posiadam.",
  "Modliłem się nad osobą chorą i doświadczyła uzdrowienia.",
  "Nie jest dla mnie problemem, gdy ludzie wpadają do mnie bez zapowiedzi.",
  "Często długo modlę się za ludzi i za ich problemy.",
  "Dużo Bożego światła w moim życiu otrzymałem przez dogłębne studiowanie różnych spraw.",
  "Odwiedzanie osób w domach opieki, szpitalach czy noclegowniach daje mi wiele satysfakcji.",
  "Mam wśród przyjaciół osoby z innych kultur/środowisk/religii.",
  "Bóg dał mi umiejętność gry na instrumencie muzycznym i bardzo sobie to cenię.",
  "Nie boję się myśli o prowadzeniu innych i formowaniu ich do posługi w Kościele.",
  "Zdarzyło mi się w życiu podjąć duże ryzyko ze względu na Boga.",
  "Doświadczyłem tego, że Bóg daje mi czasami natchnienia, by powiedzieć lub zrobić jakąś rzecz. Były tego dobre owoce.",
  "Mam radość z robienia zwykłych, prozaicznych prac dla chwały Bożej.",
  "Cieszy mnie nauczanie zarówno pojedynczych ludzi jak i grup.",
  "Mam w sercu pragnienie pisania pięknych rzecz o Bogu.",
  "Problemy mnie nie przerażają. Wprost przeciwnie - mobilizują do szukania nowych rozwiązań i działań.",
  "Lubię organizować ludzi, by ewangelizacja była owocniejsza.",
  "Nie obawiam się doradzać ludziom w sprawach duchowych i moralnych.",
  "Mam głębokie doświadczenie tego, że Jezus jest moim Oblubieńcem/Przyjacielem.",
  "Lubię tworzyć rzeczy własnymi rękami.",
  "Lubię mieć mało – daje mi to poczucie wolności.",
  "Pociąga mnie dzielenie się moją relacją z Jezusem z innymi.",
  "Mam wielu znajomych i przyjaciół. Ludzie często się przede mną otwierają.",
  "Przyjaźnię się z kapłanem/liderem i wiem, że ma we mnie wsparcie.",
  "Lubię organizować rzeczy i pieniądze dla osób w potrzebie.",
  "Modlitwa za chorych i cierpiących jest częsta w moim życiu.",
  "Ludzie lubią przebywać w moim domu. Czują się w nim dobrze.",
  "Doświadczam tego, że Bóg w namacalny sposób odpowiada na moje modlitwy.",
  "Nauczyłem się wiele o Bogu z Pisma, książek i medytacji nad życiem.",
  "Lubię pomagać ludziom bezpośrednio, bo mam głęboko w sercu słowa Jezusa, że „wszystko, co uczyliście jednemu z tych braci moich najmniejszych, mnieście uczynili”.",
  "Mam pragnienia głoszenia Ewangelii w innych krajach.",
  "Mam głębokie przekonanie, że muzyka jest doskonałym narzędziem do otwierania ludzi na Boga.",
  "Założyłem kiedyś grupę/wspólnotę, z którą podzieliłem się nową wizją ewangelizacji.",
  "Wierzę, że kiedy pełnię wolę Bożą, to Bóg działa przeze mnie.",
  "Nie szukam tego, ale czasami przychodzą mi jakieś obrazy i słowa, które ufam, że pochodzą od Boga.",
  "Kiedy jest coś do zrobienia we wspólnocie/parafii to chętnie pomagam, ale nie lubię być odpowiedzialnym.",
  "Wydaje mi się, że ludzie szybko się uczą, kiedy do nich głoszę.",
  "Mam łatwość w przelewaniu myśli na papier.",
  "Wśród problemów i zamętu staram się znaleźć przyczyny, wzorce i środki zaradcze.",
  "Lubię dzielić prace na mniejsze zadania i rozdzielać je pomiędzy ludźmi.",
  "W moim życiu ważne są relacje. Poświęcam im wiele czasu.",
  "Przychodzi mi czasami do głowy myśl, by ze względu na Jezusa i głoszenie Ewangelii nie szukać meża/żony.",
  "Mam pragnienie tworzenia pięknych rzeczy, które będą ukazywały piękno Boga.",
  "Wzrusza mnie ubóstwo Chrystusa. Mam pragnienie Go w tym naśladować.",
  "Zdarzyło mi się podzielić moim świadectwem z przypadkowo spotkanym człowiekiem.",
  "Ludzie, którzy czują się zagubieni często przychodzą do mnie po poradę i pociechę.",
  "Nie czuję się uzdolniony do pracy z grupami. Łatwiej mi wspierać pojedynczego człowieka.",
  "Kiedy nie mogą dać pieniędzy na wspieranie Bożych dzieł, staram się poświęcić na ten cel mój czas.",
  "Szczególnie dotykają mnie fragmenty Pisma Świętego, które mówią o uzdrowieniu i uwolnieniu.",
  "Staram się spędzać czas z tymi, którzy przychodzą do wspólnoty/parafii od niedawna, by poczuli się przyjęci.",
  "Mam radość z powierzania na modlitwie różnych spraw i problemów. Wiem, że Bóg się zatroszczy.",
  "Znajomość Biblii i teologii pozwala mi rozwiązywać moje problemy osobiste i wspólnotowe/parafialne/kościelne.",
  "Czuję się powołany do tego, by pomagać innym dźwigać ich ciężary i przywracać im godność.",
  "Pociąga mnie myśl o rozpoczynaniu ewangelizacji w zupełnie nowych miejscach.",
  "Cieszy mnie myśl, że moje zdolności muzyczne pomagają innym się modlić.",
  "Zdarzyło mi się, że ktoś, widząc moją posługę/ewangelizację/działalność, zaofiarował mi pomoc.",
  "Lubię powtarzać wśród problemów, że „dla Boga wszystko jest możliwe”.",
  "Zdarzyło mi się, że Bóg przez jakąś myśl, natchnienie czy sen objawił mi coś, co wydarzyło się po jakimś czasie.",
  "Mam więcej satysfakcji ze zrobienia pracy samemu niż ze zlecania jej innym. Dlatego czasami za dużo biorę na siebie.",
  "Lubię patrzeć, jak ludzie dzięki moim słowom odkrywają prawdę i zachwycają się nią.",
  "Czasami modlę się, pisząc słowa modlitwy/medytacji.",
  "Mam często w trudnych sytuacjach wiele pomysłów ich rozwiązania.",
  "Kiedy widzę brak organizacji w grupie to często jestem pierwszą osobą, która temu próbuje zaradzić.",
  "Najbardziej lubię tworzyć relacje z ludźmi przez spotkania „jeden na jeden”.",
  "Mam przyjaciół, ale żadna z relacji ludzkich nie potrafi wypełnić mojego serca.",
  "Czerpię przyjemność z projektowania, tworzenia i porządkowania rzeczy.",
  "Mam pragnienie przebywania z ludźmi ubogimi. Dobrze się wśród nich czuję.",
  "Martwią mnie ludzie z okolicy, którzy nie chodzą do kościoła. Często zastanawiam się, jak do nich dotrzeć.",
  "Lubię być wsparciem dla osób, które robią coś dobrego – umacniam ich do wytrwania w tym.",
  "Mam radość z pomagania innym w realizacji ich powołania.",
  "Mam doświadczenie tego, że kiedy hojnie daję innym, to Bóg zaspokaja moje potrzeby jeszcze hojniej.",
  "Wydaje mi się, że za mało jeszcze w Kościele modlimy się za chorych i cierpiących.",
  "Zdarzyło mi się, że otworzyłem mój dom przed kimś w potrzebie.",
  "Zdarza mi się modlić w różnych sprawach nawet w trakcie innych czynności.",
  "Jest dla mnie radością czytać i studiować nawet trudne książki, jeśli pogłębia to moją wiarę i poszerza wiedzę.",
  "Mam radość z odwiedzania osób, które z powodu chorób nie mogą wychodzić.",
  "Mam pragnienie spotykania się z ludźmi z innych krajów i kultur, by rozmawiać z nimi o Bogu.",
  "Mój spontaniczny śpiew/gra na instrumencie pomaga innym głębiej przeżyć modlitwę/wejść w modlitwę lub spotkać się z Bogiem.",
  "Mam satysfakcję z formowania ludzi, by mogli w Kościele być aktywni – korzystali ze swoich charyzmatów.",
  "Zdarzyło mi się podjąć trudne zadania we wspólnocie/parafii, z przekonaniem, że Bóg uzdolni mnie do zrealizowania ich.",
  "Mam czasami takie wewnętrzne „przynaglenie” do powiedzenia lub zrobienia czegoś.",
  "Lubię robić rzeczy w taki sposób, by nie skupiać na sobie uwagi.",
  "Jest dla mnie czymś łatwym przygotować materiały na spotkanie biblijne/spotkanie małej grupy/dzielenie się Słowem Bożym itp.",
  "Zdarzyło mi się, że ktoś docenił piękno słów, które napisałem.",
  "Mam pewną łatwość w analizowaniu problemów i wyzwań stojących przed konkretną parafią/wspólnotą oraz rozwiązywania ich."
] as const
